<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

</body>
<script>
    async function getData(num) {
        //asyncawiat : 비동기 -> 동기(과정 중에서 순서를 통해 흘러가야하는 함수를 묶는다.)
        //then 없이 사용할 수 있게 된다.
        let promise = new Promise((reslove, reject) => {
            setTimeout(() => reject(num + 10) ,100)
        });

        let promise2 = (data) => new Promise((reslove, reject) => {
            setTimeout(() => reslove(data + 10) ,100)
        });
        //reject 사용시 try{}catch{}로 감싸줘야한다.
        try{
            const result = await promise;// resolve() 실행 시까지 기다림. 결국 then이 호출되는 것
            const result2 = await promise2(result);
        }catch(error){
            console.log(error);
        }
        // return result2;
    }
    getData(10).then(x => console.log(x));
    console.log('안녕2');
</script>
</html>